#!/bin/bash

set -x

sudo bash <<EOF
set -x

dnf -y groupinstall 'C Development Tools and Libraries'
dnf -y install \
        vim \
        vim-X11 \
        ddccontrol \
        ddcutil \
        wireguard-tools \
        libsecret \
        libsecret-devel \
        git-credential-libsecret \
        xclip
EOF

git config --global credential.helper /usr/libexec/git-core/git-credential-libsecret

