export PATH="$PATH:$HOME/.local/go/bin:$HOME/.cargo/bin:$HOME/.yarn/bin:$HOME/.pnpm/bin:$HOME/.npm/bin:$HOME/.local/bin"

export EDITOR=nvim
alias vim=nvim
alias vimx=nvim

if [ -d ~/.go ]
then
        export GOPATH=$HOME/.go
fi

if [ -f ~/.cargo/env ]
then
        source ~/.cargo/env
fi

if [[ $OSTYPE == darwin* ]]
then
        export HOMEBREW_PREFIX="/opt/homebrew";
        export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
        export HOMEBREW_REPOSITORY="/opt/homebrew";
        eval "$(PATH_HELPER_ROOT="/opt/homebrew" /usr/libexec/path_helper -s)"
        [ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
        export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

        if [ "/opt/homebrew/bin/bash" == "$SHELL" ]
        then
                eval "$(/opt/homebrew/bin/brew shellenv)"
                source "/opt/homebrew/etc/bash_completion"
        fi

        source $HOME/.orbstack/shell/init.bash 2>/dev/null || :
fi

export BASH_SILENCE_DEPRECATION_WARNING=1

alias assume=". assume"

if [ -f ~/.bashrc ]
then
        source ~/.bashrc
fi

