if [ -f /etc/bashrc ]
then
	. /etc/bashrc
fi

if [ -f "$HOME/.git-prompt.sh" ]
then
	source "$HOME/.git-prompt.sh"

	GIT_PS1_SHOWDIRTYSTATE=1
	GIT_PS1_SHOWUNTRACKEDFILES=1

	PS1='\u@\h \W$(__git_ps1 " (%s)")\n  > '
else
	PS1='\u@\h \W\n  > '
fi

if [[ $OSTYPE == darwin* ]]
then
  source "$HOME/.bashrc_darwin"
fi

