if [ -f /etc/bashrc ]
then
	. /etc/bashrc
fi

if [ -f "$HOME/.git-prompt.sh" ]
then
	source "$HOME/.git-prompt.sh"

	GIT_PS1_SHOWDIRTYSTATE=1
	GIT_PS1_SHOWUNTRACKEDFILES=1

	PS1='\u@\h \W$(__git_ps1 " (%s)")\n  > '
else
	PS1='\u@\h \W\n  > '
fi

# Ghostty shell integration for Bash. This should be at the top of your bashrc!
if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
    builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/bash/ghostty.bash"
fi


if [[ $OSTYPE == darwin* ]]
then
  source "$HOME/.bashrc_darwin"
fi

